# Generated by Django 2.1.5 on 2019-02-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='file')),
            ],
        ),
    ]
