# Generated by Django 2.1.7 on 2019-02-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_auto_20190226_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
